server {
    listen 80;
    listen [::]:80;
    server_name www.gezhixin.cn;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name www.gezhixin.cn;

    ssl_certificate /etc/letsencrypt/live/www.gezhixin.cn/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/www.gezhixin.cn/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 1d;

    location / {
        proxy_pass https://home.gezhixin.cn:4430;
        proxy_http_version 1.1;
        proxy_ssl_server_name on;
        proxy_ssl_name home.gezhixin.cn;
        proxy_set_header Host home.gezhixin.cn:4430;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-Host $host;
        proxy_connect_timeout 10s;
        proxy_read_timeout 60s;
        proxy_send_timeout 60s;
    }
}
